services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\Blocks\:
    resource: '../src/{ContentElement,Controller,DataContainer,EventListener,Exception,Model,Module}/*'

  HeimrichHannot\Blocks\ContentElement\:
    resource: '../src/ContentElement/*'
    autowire: false

  HeimrichHannot\Blocks\DataContainer\:
    resource: '../src/DataContainer/*'
    public: true

  HeimrichHannot\Blocks\Controller\Backend\Content:
    public: true
