services:
  HeimrichHannot\Blocks\:
    resource: '../src/{Backend,ContentElement,Controller,DataContainer,EventListener,Exception,Model,Module}/*'
    autowire: true
    autoconfigure: true
    public: true
