services:
  HeimrichHannot\Blocks\:
    resource: '../src/{Backend,ContentElement,Controller,DataContainer,EventListener,Exception,Model,Module}/*'
    autowire: true
    autoconfigure: true

  HeimrichHannot\Blocks\EventListener\InsertTagsListener:
    public: true
